name: Invia Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-focal

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        npm install
        npx playwright install 
  
    - name: Run DE prod tests
      run: npm run e2e:prod:de     

    - name: Run AT prod tests
      run: npm run e2e:prod:at

    - name: Run CH prod tests
      run: npm run e2e:prod:ch

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report/