name: Invia Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.48.1-noble
    env:
      HOME: /root

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        npm install --production
        npx playwright install 
  
    - name: Run DE prod tests
      run: npm run e2e:prod:de     

    - name: Run AT prod tests
      run: npm run e2e:prod:at

    - name: Run CH prod tests
      run: npm run e2e:prod:ch

    - name: Create report directories
      run: mkdir -p playwright-report-de playwright-report-at playwright-report-ch

    - name: Upload all Playwright reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-reports
        path: |
          playwright-report-de/
          playwright-report-at/
          playwright-report-ch/